---
# An example of basic hosts-file configuration where first node hosts orderer
all:
  hosts: # localhost connection parameters, used for storing configuration while transferring it between nodes
    localhost:
      ansible_connection: local
  vars:
    domain: example.com
    orderer_type: solo
  children:
    nodes:
      hosts:
        orderer.example.com:
          node_roles: # Describes which containers will run on this node
            - root_orderer
            - orderer
            - peer
            - root_peer
            - explorer
          org: mainorg # Organization name
          ansible_host: node0 # Real ip address or domain name of the machine
          ansible_user: root
          # Same structure for any other nodes
        one.example.com:
          node_roles:
            - peer
          org: one
          ansible_host: node1
          ansible_user: root
        two.example.com:
          node_roles:
            - peer
          org: two
          ansible_host: node2
          ansible_user: root
        three.example.com:
          node_roles:
            - peer
          org: three
          ansible_host: node3
          ansible_user: root
